## Deepfake Detection Platform Configuration

# General settings
general:
  log_level: INFO
  debug_mode: false
  result_cache_size: 100
  max_threads: 4
  temp_dir: "./temp"

# Model settings
models:
  image:
    model_name: "google/vit-base-patch16-224"
    confidence_threshold: 0.7
    use_gpu: true
    batch_size: 16
  
  audio:
    model_name: "facebook/wav2vec2-large-960h"
    confidence_threshold: 0.65
    use_gpu: true
    sample_rate: 16000
  
  video:
    frame_model_name: "google/vit-base-patch16-224"
    temporal_model_name: "facebook/timesformer-base-finetuned-k400"
    confidence_threshold: 0.75
    use_gpu: true
    frames_per_second: 5
    segment_length: 10

# User interface
ui:
  theme: "tron_legacy"
  max_history_items: 20
  auto_refresh: true
  default_tab: "image"

# Processing
processing:
  queue_size: 10
  auto_save_results: true
  save_processed_media: false
  detection_timeout: 300

# Reporting
reports:
  save_directory: "./reports/output"
  generate_pdf: true
  include_visualizations: true
  confidence_decimal_places: 2
