## Deepfake Detection Platform Configuration

# General settings
general:
  log_level: INFO
  debug_mode: false
  result_cache_size: 100
  max_threads: 8
  temp_dir: "./temp"
  # CUDA configuration
  cuda_enabled: true
  cuda_device: "cuda:0"
  cuda_memory_limit_gb: 4.0
  prefer_gpu_id: 0
  fallback_to_cpu: true
  mixed_precision: true
  distributed_training: false

# Model settings
models:
  image:
    model_name: "google/vit-base-patch16-224"
    confidence_threshold: 0.7
    use_gpu: true
    batch_size: 16
    gpu_optimization:
      half_precision: true
      compile_model: true
    # Alternative models available:
    # - "microsoft/beit-base-patch16-224-pt22k-ft22k"
    # - "microsoft/swin-base-patch4-window7-224-in22k"
  
  audio:
    model_name: "facebook/wav2vec2-large-960h"
    confidence_threshold: 0.65
    use_gpu: true
    sample_rate: 16000
    gpu_optimization:
      half_precision: true
      compile_model: true
  
  video:
    frame_model_name: "google/vit-base-patch16-224"
    temporal_model_name: "facebook/timesformer-base-finetuned-k400"
    confidence_threshold: 0.75
    use_gpu: true
    frames_per_second: 5
    segment_length: 10
    gpu_optimization:
      half_precision: true
      compile_model: true
      batch_process_frames: true

# User interface
ui:
  theme: "tron_legacy"
  max_history_items: 20
  auto_refresh: true
  default_tab: "image"

# Processing
processing:
  queue_size: 10
  auto_save_results: true
  save_processed_media: false
  detection_timeout: 300

# Reporting
reports:
  save_directory: "./reports/output"
  generate_pdf: true
  include_visualizations: true
  confidence_decimal_places: 2
